### ISSUE TITLE
Cant place in liquid

### ISSUE THREAD

**Issue by dbock1989** [SejoslawMods/CatchEverythingInBook#1]
I love this mod!!!

Although, I can "catch" things in water but cannot replace it in water.

Using version 1.14.4 1.0.0 forge

**Comment by Sejoslaw** [comment]
By "things" you mean Entities or Blocks ?

**Comment by dbock1989** [comment]
Im sorry for not being clear! 
By things I meant blocks. I picked up a stone block in the water by accident, and tried to re place it in the same spot but it would not place. I went to the surface to try to get it out of the book and placed just fine. After a few more attempts, I determined it was due to the water (or liquid).

**Comment by Sejoslaw** [comment]
Yeah, probably.
I just base on Forge / Fabric HitResult or BlockHitResult.
Maybe this is how they interpret that under water.
I'm not sure if I can do anything about it :P
I can take a look anyway.

**Comment by dbock1989** [comment]
Either way, you made a fantastic mod. I do hope you find a fix, but it isn't a deal breaker. Keep up the great work!

**Comment by Sejoslaw** [comment]
Thx ^^
